package.json, src/index.d.ts
This is a WIP draft. Feedback and contributions are very welcome! This relates to https://github.com/supabase/supabase/issues/122
e.g. this could look like
```ts
interface Message {
id: number;
inserted_at: string;
message: string;
channel_id: number;
author?: { name: string };
}
// Resolves with messages: any
const { body: messages } = await supabase
.from('messages')
.select('some_column, other_column')
// Resolves with messages: Array<Message>
const { body: messages } = await supabase
.from<Message>('messages') // Message is the type of row in database
.eq('channel_id', 1) // IDE will be able to help with the completion of channel_id
.select(`*, author:user_id(id, username)`) // Not sure if we can do much autocompletion here
.order('inserted_at', true); // IDE will help with …
```
=> Add type definitions.

RELEASE.md, package-lock.json, package.json
- Bump postgrest-js dependency to pull in the order by JSON column data fix (https://github.com/supabase/postgrest-js/pull/132).
=> fix: Ordering by data in JSON columns.

src/index.ts
feature: #97 
The library does not export all types needed for use in client side TypeScript projects.
Export the additional types for use in client side projects.
Note: This PR cannot be merged until the gotrue-js PR is merged: https://github.com/supabase/gotrue-js/pull/29
=> feat: add type exports for client side use

src/index.ts
In order to get the `User` type, I had to do a import like this
```
import { User } from '@supabase/gotrue-js/dist/main/lib/types'
```
so I thought it would be better to export `User` from supabase-js
`User` is not exported within supabase-js
`User` is exported as `AuthUser`. Developers should be able to import the `AuthUser` type like this:
```
import { AuthUser } from "supabase-js";
```
=> Added 'User' to the exports

src/lib/SupabaseQueryBuilder.ts, src/lib/SupabaseRealtimeClient.ts, src/lib/types.ts
Add a new Type to avoid use duplicated code.
We're duplicating code for lack of specific data type.
Creating this new type, we can remove the duplicated code using the new created type.
JS is amazing, isn't?
=> feat: add EventTypes as a Type

src/SupabaseClient.ts
Refactor/Update [`_initSupabaseAuthClient`](https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts#L122) method.
This refactor doesn’t change the current behaviour.
- [Destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
=> refactor: add object destructuring on _initSupabaseAuthClient method

package.json
Feature/fix
The package is not currently marked as side effect free so tree-shaking will be limited.
Tree-shaking can be done properly.
---
I didn't see anything that has side effects in the package, but if you know any then this should not be done
=> Add `"sideEffects": false` to pkg.json

src/SupabaseClient.ts, src/lib/SupabaseRealtimeClient.ts
This PR will help us to reduce the complexity of the SupabaseRealtimeClient and SupabaseClient classes splitting our current code.
- SupabaseRealtimeClient -> getPayloadRecords method complexity is 10.
- SupabaseClient class complexity is 11.
- SupabaseClient -> removeSubscription method complexity is 11.
SupabaseRealtimeClient -> getPayloadRecords method complexity will be 7.
- SupabaseClient class complexity will be 10.
- SupabaseClient -> removeSubscription method complexity is 10.
=> refactor: reducing the complexity of the SupabaseRealtimeClient and SupabaseClient classes

package-lock.json, package.json
Feature.
Support `or` embedded filter as per https://github.com/supabase/postgrest-js/pull/160.
=> feat(postgrest-js): support `or` embedded filter

package-lock.json, package.json
Update postgrest-js lib to the latest major version.
Included releases:
https://github.com/supabase/postgrest-js/releases/tag/v0.26.1
https://github.com/supabase/postgrest-js/releases/tag/v0.26.0
=> chore: update postgrest-js to include next major version

example/next-storage/README.md, example/next-storage/components/Account.tsx, example/next-storage/package.json
Added sample storage policies to the next-storage example app's readme.md
There are no example policies to get started with. 
There are SQLs that users can run to get up and running with Supabase Storage!
I added typescript dependencies to the project, because it was missing, but let me know if this was unnecessary.
=> Added storage policies to readme.md of next-storage example app

example/next-storage/components/Account.tsx, example/next-storage/components/Avatar.tsx, src/SupabaseClient.ts, src/lib/SupabaseStorageClient.ts, src/lib/storage/StorageApi.ts, src/lib/storage/StorageBucketApi.ts, src/lib/storage/StorageFileApi.ts, src/lib/storage/index.ts, test/storageApi.test.ts
Separating `StorageBucketApi` and `StorageFileApi`, so that we can call storage api with this syntax
```
supabase.storage.from('avatars').downloadFile('avatar1.png')
```
=> refactor: SupabaseStorageClient

src/lib/storage/StorageFileApi.ts
this mirrors the default limit in the backend
Fixes issue reported at https://github.com/supabase/supabase/discussions/996
=> fix: change default limits for listing objects to 100

src/lib/storage/StorageFileApi.ts
fixes https://github.com/supabase/supabase-js/issues/148
Previous return value for `createSignedURL`
```
{
"data": {
"signedURL": "/object/sign/test/test.png?token=blahblahblah",
"signedUrl": "https://example.supabase.co/storage/v1undefined",
"error": null
}
}
```
New return value
```
{
"data": {
"signedURL": "https://example.supabase.co/storage/v1/object/sign/test/test.png?token=blahblahblah",
"error": null
}
}
```
=> feat: updates createSignedURL to return full URL

src/lib/storage/StorageFileApi.ts, src/lib/storage/fetch.ts
- Integrate AbortController signals to storage`fetch` methods (GET, POST, PUT, REMOVE)
- Allow `list` endpoint to accept a signal parameter
Some context: 
An initial optimization I added on the storage UI when we were directly calling the endpoints via the fetch method was to add an [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController), so that FE can cancel API calls if they have not completed.
This is particularly useful such that if the user opens a folder (which triggers a POST request to list the items in a bucket by a path), but then opens another folder immediately while the previous POST request is still in progress, the previous POST request will be cancelled and the latest POST request  will be taken instead. With this, the UI won't have any …
=> Integrate AbortController signals to storage fetch methods for APIs

src/lib/storage/StorageFileApi.ts
Fixes the types for createdSignedURL. 
Also exposes it as a property outside `data` so that the URL can be accessed like
```js
const { signedURL, error } = await supabase.storage.createSignedURL('cat.png', 60) 
```
=> fix: types for create signed URL; copy it as a prop outside

src/lib/storage/StorageFileApi.ts
Previously the project ref was also returned in upload and update calls. This doesn't make a sense for the user as it is more of an implementation detail. This has already [been fixed](https://github.com/supabase/storage-api/commit/ff08bdf4a925dd500a8f5be3ced769c657bbfd47) in storage-api. This is a temporary patch till the fix gets rolled out to everyone.
=> fix: remove projectref returned from upload and update object

src/lib/SupabaseRealtimeClient.ts
Parameter of callback function of on() should have SupabaseRealtimePayload type instead of any Function.
Type error fix. Solves the #179. Detailed information is given in issue.
callback function has type Function which can be replaced with `(payload: SupabaseRealtimePayload<T>) => void`
#179
=> fix: type error for callback of on() in SupabaseRealtimeClient

package-lock.json, package.json
fixes our failed CI runs like https://github.com/supabase/supabase-js/runs/2673094175
Later, we should update the `npm run docs` to make it work with the latest typedoc.
=> revert typedoc to a previous version

package-lock.json, package.json
Implement unwrap() to throw query errors instead of returning them: https://github.com/supabase/postgrest-js/pull/188
fix: change match's value type to unknown: https://github.com/supabase/postgrest-js/pull/192
Closes #203.
=> Bump postgrest-js

package-lock.json, package.json
Bug fix
client receiving a large influx of messages from realtime server prevents client from sending heartbeat back, which will cause disconnect.
client will reset its heartbeat interval after receiving message from realtime server, preventing disconnect when receiving large influx of messages.
=> fix: version bump realtime-js to v1.0.11

src/SupabaseClient.ts
Fix the rpc count missing in the function
`supabase.rpc('fnc_name', { params }, { count: "exact" })` is missing the count object parameter.
Fix the function, able to create rpc function that return `count`
=> Fixes supabase/supabase-js#236

src/SupabaseClient.ts
Feature
When we instantiate SupabaseClient it is possible to specify additional headers to use in any API request :
https://github.com/supabase/supabase-js/blob/c5310d69cada1cb72b8d698d8a27c8a9590898d3/src/SupabaseClient.ts#L44
These headers don't seem to be actually used at all.   
Gotrue allows to specify the audience of the users during requests, by setting a header 'X-JWT-AUD' containing the audience, but we cannot use this feature yet because when SupabaseClient instantiates the GotrueClient, it doesn't forwards the custom headers to it.
When SupabaseClient instantiates the GotrueClient, it forwards the custom additional headers to the GotrueClient. It is now possible to set the 'X-JWT-AUD' header in every request to Gotrue.
=> Use additional headers from SupabaseClient into GotrueClient.

package-lock.json, package.json
This version of postgrest-js includes the following fixes:
- https://github.com/supabase/postgrest-js/pull/210
- https://github.com/supabase/postgrest-js/pull/212
=> fix: bump postgrest-js

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/SupabaseAuthClient.ts, src/lib/types.ts
It's a follow up to: https://github.com/supabase/gotrue-js/pull/117 - just adjusting how options are passed around so one can leverage those downstream changes.
=> Access localStorage lazily to avoid DOMExceptions in constrained envs when `localStorage` is provided using options

src/SupabaseClient.ts
This PR will override the `X-Client-Info` header of `postgrest-js` and `storage-js` just like how it is already doing for `realtime-js` and `gotrue-js`. 
Related https://github.com/supabase/supabase-js/pull/238
`supabase-js` does not override the `X-Client-Info` header of `postgrest-js` and `storage-js`. 
`supabase-js` does override the `X-Client-Info` header of `postgrest-js` and `storage-js`. 
If not overriding the headers of `postgrest-js` and `storage-js` is intentional, please feel free to close this P.
=> fix: Override X-Client-Info header for postgrest-js and storage-js

src/lib/SupabaseQueryBuilder.ts, src/lib/SupabaseRealtimeClient.ts
feature
Pass the user access token to Realtime in order to apply RLS on a per topic basis via [WALRUS](https://github.com/supabase/walrus).
Related issue: https://github.com/supabase/walrus/issues/4
=> feat: add user_token when creating realtime channel subscription

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .releaserc.json
- update to node16 from 12 (semantic-release now requires at least node14)
- disable commenting on PRs/issues included in the release (semantic release seems to be running into some github API issue)
Could pin to the last major release of semantic release to avoid bumping node versions for a little while.
=> chore: fix CI release process

src/SupabaseClient.ts, src/lib/helpers.ts
Feature
A trailing slash in the `supabaseUrl` causes duplication in the final URL
A trailing slash is removed from the `supabaseUrl` so the created URL does not contain duplicates
- The regex only accounts for a single `\`. 
- Another option would be to update the docs, but this improves DX as there is no need to worry about if a slash should be appended to the URL or not
- fixes https://github.com/supabase/supabase-js/issues/261
=> Allow for trailing slash in supabaseUrl

package-lock.json, package.json, src/SupabaseClient.ts
Feature.
RPC calls do not permit `HEAD` requests.
Bumps `postgrest-js` and permits `HEAD` requests for RPC calls.
See https://github.com/supabase/postgrest-js/pull/215.
=> feat: allow `HEAD` requests for RPC calls

README.md, src/SupabaseClient.ts, src/lib/SupabaseQueryBuilder.ts, src/lib/types.ts
This PR adds the ability to provide a custom `fetch` implementation as an option - this is most useful for environments where `cross-fetch` is not supported, for instance Cloudflare Workers or Vercel Edge Functions.
This is related to https://github.com/supabase/supabase-js/issues/154 and depends on the following PRs in the wrapped client libraries:
- https://github.com/supabase/postgrest-js/pull/222
- https://github.com/supabase/gotrue-js/pull/168
- https://github.com/supabase/storage-js/pull/24
All three of those PRs would need to be merged before this PR builds correctly / functions.
At the moment, `cross-fetch` is always used in all environments.
There is a new option `fetch` that can be provided to override `cross-fetch` with an alternative library (or the native `fetch`):
```js …
```
=> feat: allow providing custom fetch implementation

test/SupabaseAuthClient.test.ts, test/client.test.ts, test/constants.test.ts
Shall we start the test battery together?
=> tests: create some generic tests

src/SupabaseClient.ts
We want to pass custom `fetch` to gotrue-js, but the value is not yet
set when we run `_initSupabaseAuthClient()`. Solution: set custom
`fetch` before running `_initSupabaseAuthClient()`.
=> fix: missing fetch during auth init

src/SupabaseClient.ts, test/client.test.ts
Feature
Since https://github.com/supabase/supabase-js/pull/218 custom headers passed to the `SupabaseClient` constructor are passed on to the `GoTrueClient`. 
However they are not passed on to the`PostgestClient`, `SupabaseStorageClient` and `SupabaseQueryBuilder`, although implied by the param description: 
https://github.com/supabase/supabase-js/blob/5f7f3d5f088d213ae56e9a806066c1c810c852ab/src/SupabaseClient.ts#L45
Headers passed through the `options.headers` parameter of the constructor are now stored in a new protected variable `headers`. Since all clients mentioned above call the private method `_getAuthHeaders` I decided to inject the custom headers here, together with the default headers that were already injected inside this method. 
I also created a very minimal test case, just …
=> Use custom headers in every client

package.json
Bug fix
run `npm update` and `realtime-js` is the latest version (`1.3.2`). However, Realtime RLS currently does not work with `realtime-js` past version `1.2.1`.
Restrict `realtime-js` to version `1.2.1`
=> fix: restrict realtime-js to v1.2.1

README.md
This updates the documentation example of providing a custom `fetch` implementation (introduced in https://github.com/supabase/supabase-js/pull/297). While the previous example was conceptually correct, in most environments it's not possible to assign a native built-in function like `fetch` to an object, as calling it later will attempt to call the native function in the context of the object and throw an `illegal invocation` error.
Creating a new fetch function by binding to the global scope, for instance `fetch.bind(global)` in Node or `fetch.bind(self)` in Cloudflare Workers, fixes this issue, but creating a new arrow function is the most univerally functional example since it doesn't require you to know if `global` is defined or not, so this PR uses that as an example:
```js
{
fetch: …
```
=> fix(docs): update custom fetch example

src/SupabaseClient.ts
Bug fix
`removeAllSubscriptions` function breaks React Native apps b/c `Promise.allSettled` is absent.
Refactor `removeAllSubscriptions` to use `Promise.all` instead of `Promise.allSettled`.
Related: https://github.com/supabase/supabase/discussions/5058#discussioncomment-2001082
=> fix: refactor removeAllSubscriptions to use Promise.all

src/SupabaseClient.ts, src/index.ts, src/lib/SupabaseQueryBuilder.ts, src/lib/types.ts
Refactor our codebase creating a new type to avoid repeat ourselves and add the correct return type for createClient method
=> refactor: create a new type to avoid repeat ourselves and add the correct return type for createClient method

.github/workflows/release.yml
this ensures that the files served by CDN networks based on
minified files published report the correct version, rather than the
placeholder '0.0.0'.
I _think_ this works, but its hard to test.
=> fix: update version before minified output is generated

src/lib/types.ts
TS support for **multiTab** in the third argument in **createClient**
```
createClient(
SUPABASE_URL,
SUPABASE_SECRET_KEY,
{ multiTab: false }
)
```
=> fix: add multiTab TS support during createClient

src/SupabaseClient.ts
When initializing SupabaseClient, if the `Authorization` header is provided, it will be used for `_getAuthHeaders()` instead of the session's access token or Supabase key.
=> fix: allow overriding Bearer token

src/SupabaseClient.ts
* [feat(functions): set fetch on the underlying client](https://github.com/supabase/supabase-js/commit/05a5083a4bfade348476b5293ae0ba72c6b19161)
* [fix(client): getter always returns a new FunctionsClient instance](https://github.com/supabase/supabase-js/commit/951ece5fb77f8d5e8fa3654319393004beab1690)
=> feat(functions): add fetchImpl on FunctionsClient initialization

jest.config.js, src/SupabaseClient.ts, test/client.test.ts
Bug fix
https://github.com/supabase/supabase-js/pull/402 caused a regression in the client that will cache the initial Authorization header
Still allows overriding the Authorization header, but otherwise will use the value from `auth.session()`
=> fix: do not cache Authorization header (and add tests)

.github/workflows/release.yml, .releaserc.json
Build
There is currently no prerelease pipeline.
Pushes to the next branch will be included as an npm prerelease under the next tag.
This setup is working in here: https://github.com/supabase/gotrue-js/pull/293
=> build: sets up the next branch as an npm prerelease

.github/workflows/release.yml, .releaserc.json, package-lock.json, package.json, src/SupabaseClient.ts, src/lib/fetch.ts, test/client.test.ts
Feature/chore
Currently using the old method of setting auth headers
Uses `gotrue-js`'s `getSession()` method for asynchronously getting the token
This is using a prerelease version of `gotrue-js`, so should **not** be merge into master.
Also, suggestions for more/better tests are welcome!
=> feat: use getSession from gotrue-js

src/SupabaseClient.ts, src/lib/types.ts
Remove MultiTab option as it has been removed in [GoTrue-js](https://github.com/supabase/gotrue-js/pull/366/files)
=> Remove Multitab from constructor

src/SupabaseClient.ts, src/lib/types.ts
Till all the client libraries support this option.
Once they do, we can add this option back in to the parent library as a non-breaking change
=> temporarily remove shouldThrowOnError

package-lock.json, package.json
Bumps:
- `gotrue-js` to `^1.23.0-next.12`
- `storage-js` to `^1.8.0-next.3`
=> fix: bump gotrue-js and storage-js next versions

package-lock.json, package.json, src/SupabaseClient.ts
Bug fix
Bumps storage-js to 1.8.0-next.4 and changes the import from `SupabaseStorageClient` to `StorageClient` (see supabase/storage-js/pull/92)
When installing `@supabase/supabase-js@1.36.0-next.14` it installs `@supabase/storage-js@1.8.0-next.4` and the import is broken.
```bash
$ npm install --save @supabase/supabase-js@1.36.0-next.14
$ npm list @supabase/storage-js
my-awesome-app@1.0.0 /Users/pixtron/projects/my-awesome-app
└─┬ @supabase/supabase-js@1.36.0-next.14
└── @supabase/storage-js@1.8.0-next.4
```
=> fix: bump storage-js to 1.8.0-next.4

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/types.ts
`@supabase/functions-js`: `^1.4.0-next.1` -> `^1.4.0-next.5`
`@supabase/gotrue-js`: `^1.23.0-next.15` -> `^1.23.0-next.20`
`@supabase/postgrest-js`: `^1.0.0-next.6` -> `^1.0.0-next.7`
`@supabase/storage-js`: `^1.8.0-next.5` -> `^1.8.0-next.6`
=> fix: bump next versions of dependencies

package-lock.json, package.json, src/SupabaseClient.ts
* Bump supabase-js/next to use the latest gotrue-js/next version
=> fix: bump gotrue js

package-lock.json, package.json
Bug fix
Developing in React/NextJS Strict Mode causes Realtime channel to close due to rapid mount -> unmount -> mount cycle.
Realtime channel is is successfully connected despite Strict Mode.
Related issue: https://github.com/supabase/realtime-js/issues/169
=> fix: bump realtime-js version to 2.0.0-rc.5

src/SupabaseClient.ts, src/lib/helpers.ts, test/helper.test.ts
feature
Trailing white space(s?) are not trimmed from URL.  Recently there was a [question in discord](https://discord.com/channels/839993398554656828/1004278230427107328), where the URL looked like this:
`https://{REF}.supabase.co/%20/rest/...`
Trailing white spaces are trimmed.
=> Remove trailing whitespace from url

src/SupabaseClient.ts, test/client.test.ts
Bug fix
If the supabase url passed to the client contains upercase chars in the protocol, the realtime url does not switch protocols from `http | https` to `ws | wss`. 
See this issue in realtime-js: supabase/supabase-js#531
Case is ignored when replacing `http` with `ws`. 
Another option could be to clean the whole supabase url with `url.toLowerCase()`.
=> fix: ignore case when creating realtime url

src/SupabaseClient.ts
Fix typo in JSDoc for PostgREST -> rpc call
parameters had old names
JSDoc for PostgREST rpc call is up to date
=> fix typo in rpc call doc

src/SupabaseClient.ts, test/SupabaseAuthClient.test.ts
* Fixes a bug with `_initSupabaseAuthClient` where it overwrites the custom `Authorization` header passed into `SupabaseClient` with the default authorization header (the supabase key)
* The auth client should be using the custom `Authorizaion` header instead
=> fix: custom authorization header should not be overwritten

docs/v1/modules/lib_types.html, docs/v1/spec.json, src/lib/types.ts
=> docs: add default values to client initialization

src/SupabaseClient.ts
Resolves the last remaining issue of, and closes https://github.com/supabase/gotrue-js/issues/524
After a user is logged out, the supabase-js client's `changedAccessToken` property still contains the user's jwt.
`this.changedAccessToken` is set to `undefined`, per typing.
If a `TOKEN_REFRESHED` or `SIGNED_IN` event occurs, `_handleTokenChanged` sets `this.changedAccessToken` (under the proper conditions). So I assume `_handleTokenChanged` is the place to unset `this.changedAccessToken` if a `SIGNED_OUT` event occurs.
=> fix: clear this.changedAccessToken after signOut

package-lock.json, package.json
Bumps gotrue-js to 2.12.0 which includes `supabase.auth.signInWithIdToken` and some additional improvements.
=> feat: bump gotrue-js to 2.12.0

package-lock.json, package.json
Bumps GoTrue-js version to v2.16.0 which includes WhatsApp release.
=> Bump GoTrue-js to v2.16.0

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/types.ts
`USER_DELETED` event was removed as it was deprecated, additional option `flow_type` passed in
Relevant PRs: 
User deleted event removed: https://github.com/supabase/gotrue-js/pull/653
PKCE settting: https://github.com/supabase/gotrue-js/pull/646
Note, we should also check that the latest changes on GoTrue-js don't break anything before merging, seems like build is failing. Putting this out here to solicit early feedback
=> feat: bump gotrue to v2.20

src/SupabaseClient.ts
just used a better way to define optional params instead of writing `undefined` explicitly
=> chore: type for optional params

package-lock.json, package.json
=> feat: bump gotrue-js to v2.31.0

package-lock.json, package.json
v2.45.0 has some issues with waiting for the `_initialize` promise that breaks some flows. We're pinning to v2.43.1 as this one does not suffer from any issues.
=> feat: roll back to fixed gotrue-js 2.43.1 until 2.45.0 is fixed

package-lock.json, package.json
Bumps `@supabase/gotrue-js` to `^v2.46.1` after issues discovered with #817.
=> feat: bump @supabase/gotrue-js to ^v2.46.1

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/types.ts, test/client.test.ts, test/types.ts
Resolves https://github.com/supabase/postgrest-js/issues/280
Feature
Currently, the supabase client is created and defaults to the `public` schema when no option is supplied:
```ts
createClient(supabaseUrl, supabaseKey)
```
Or, you can supply an alternative schema:
```ts
createClient(supabaseUrl, supabaseKey, {
db: {
schema: 'alternative'
}
})
```
However, this means that all methods/queries for the client are associated to the single schema. Using multiple schemas requires multiple clients, which presents a challenge for auth where all clients need to be authenticated.
See pre-existing issue:
https://github.com/supabase/postgrest-js/issues/280
Extends on behavior added to underlying `PostgrestClient`: https://github.com/supabase/postgrest-js/pull/455
The method added to the supabase …
=> Add dynamic schemas on a per-query basis

package-lock.json, package.json
Bug fix
Realtime access token is not set on client instantiation.
Realtime access token is set on client instantiation.
- https://github.com/supabase/realtime-js/pull/245
=> fix: version bump realtime-js to 2.7.4

src/lib/constants.ts, test/constants.test.ts
More granular tracking of supabase-js usage environment. 
All usage is tracked as supabase-js
different environments Deno, Web, ReactNative, Node are appended to the clinet-info header. 
=> fix: track javascript environment.

package-lock.json, package.json, src/lib/types.ts
Bumps `@supabase/gotrue-js` to v2.53.0.
=> feat: bump `@supabase/gotrue-js` to v2.53.0

package-lock.json, package.json
Bumps `@supabase/gotrue-js` to v2.54.0.
=> feat: bump `@supabase/gotrue-js` to v2.54.0

package-lock.json, package.json
Bump up realtime-js version to 2.8.4
=> fix: Bump up realtime-js version to 2.8.4

package-lock.json, package.json
Includes fix done to `postgrest-js` in https://github.com/supabase/postgrest-js/pull/506
=> fix: bump postgrest-js to 1.8.6

src/index.ts, src/lib/types.ts
In combination with https://github.com/supabase/postgres-meta/pull/654 we're adding these helpers to streamline TypeScript Types.
=> feat: add query result type helpers.

package-lock.json, package.json
* Bump gotrue-js version to [v2.60.0](https://github.com/supabase/gotrue-js/releases) which includes the new identity linking methods and weak password errors
=> fix: bump gotrue-js version

package-lock.json, package.json, src/SupabaseClient.ts
We're currently duplicating passing the type params to postgrest-js classes - we may change the order and/or add new type params on the postgrest-js side, so the type params in supabase-js can get out of sync.
This also fixes the issue in this [demo](https://github.com/daichi5/supabase-demo/blob/91385f2c1d509109938cb0e02d2a3b00201cf044/src/index.ts#L12) (`users` in `data` should be `T[]`, not `T | null`).
=> fix: stop using unstable type params from postgrest-js

package-lock.json, package.json
Bug fix
See: https://github.com/supabase/realtime-js/pull/273
=> fix: version bump realtime-js to v2.9.2

src/SupabaseClient.ts, src/index.ts, src/lib/constants.ts, src/lib/types.ts
removed some redundant code and did small refactors.
=> chore: did some refactoring

package-lock.json, package.json
Fixes the following issue by preventing the latest versions of postgrest-js by preventing supabase-js from accepting dependency versions above the tested working version. https://github.com/supabase/postgrest-js/issues/449
Arbitrary versions allow the version to update, causing unintended breaking changes (as explained in the issue)
```diff
"@supabase/functions-js@^2.1.0":
-  version "2.1.1"
+ version "2.1.2"
dependencies:
cross-fetch "^3.1.5"
"@supabase/gotrue-js@2.43.1":
version "2.43.1"
resolved "https://registry.yarnpkg.com/@supabase/gotrue-js/-/gotrue-js-2.43.1.tgz#4623791433f0b7ef4c17f0d880fba1f0307b4c81"
integrity sha512-HVjjElEPbM5sDoK1pXry/H181X7A1a9G9O68PZwN276y/EUwWOw3pA8KKKSRTaTSiK+41BPC8HUfsfbe7470RQ==
dependencies:
cross-fetch "^3.1.5"
"@supabase/postgrest-js@^1.7.0":
- …
```
=> Set functions-js and postgrest-js versions to exact

package-lock.json, package.json
Adds a script to serve the generated coverage html locally
=> feat: add serve:coverage script

src/SupabaseClient.ts
`rest` is already `PostgrestClient<Database, SchemaName>`, so all return types should be infered in the same way as before without using explicit return types.
(I changed `FnName` and `Fn` so it fits on one line, as VSCode is messing up syntax highlighting when generics are split into multiple lines 👀 )
=> fix: Use class methods instead of bound arrow functions for rest calls

src/SupabaseClient.ts
Use `ReturnType` as we implement those methods as a pass-through.
Tbh why this isn't inferred correctly by TypeScript is beyond me...
Verified on our own API repository this time to make sure it works correctly for all cases.
Fixes https://github.com/supabase/supabase-js/issues/974
Fixes https://github.com/supabase/supabase-js/pull/973#issuecomment-1942141729
=> fix: Use explicit return type for from/schema/rpc

src/lib/fetch.ts
Fixes ```A spread argument must either have a tuple type or be passed to a rest parameter.ts(2556)```
Not explicitly typed, sometimes the compiler will interpret the type wrong.
Explicit type specified.
=> hotfix:ts-error-fetchprotocol

src/SupabaseClient.ts, test/index.test-d.ts
Please take this as a sort of a question because I'm new to supabase. (and I'm aware of the `// NOTE: signatures must be kept in sync with PostgrestClient.from`).
I want to query supabase using the client and want to do that with the best possible guidance from TS.
Right now, TS (although it will suggest valid table names) won't complain if I try to query a non-existent table.
To me, this is a fairly unexpected limitation and I don't understand why it's there.
So I'm suggesting this change here (I can also make it in the other place) with the aim of achieving higher code safety.
If this is not possible, why? (Are there other cases like this, with low-hanging fruit for TS improvements?)
Thank you! :)
=> feat: typecheck table names in from clause

package-lock.json, package.json, src/SupabaseClient.ts, src/index.ts, src/lib/SupabaseAuthClient.ts, src/lib/types.ts
* Bump auth to v2.63.0 which includes the `signInAnonymously` method
=> fix: bump auth to v2.63.0

package-lock.json, package.json, src/SupabaseClient.ts
=> fix(postgrest-js): typings for rpc with GET

package-lock.json, package.json
Bug fix
realtime-js PR: https://github.com/supabase/realtime-js/pull/290
=> fix: version bump realtime-js to 2.9.4

package-lock.json, package.json
Updates functions-js dependency to 2.3.0
=> fix: bump functions-js

package-lock.json, package.json
* see [changelog](https://github.com/supabase/auth-js/releases/tag/v2.63.1)
* addresses #1010
=> fix: bump auth-js to v2.63.1

package-lock.json, package.json
bump
* "@supabase/auth-js": "2.64.0",
* "@supabase/functions-js": "2.3.1",
=> fix: bump auth-js and functions-js.

package-lock.json, package.json, src/SupabaseClient.ts
* supabase-js sets the `hasCustomAuthorizationHeader` property internally when instantiating the auth client so that auth knows whether to return an error when `getUser` is called with no session and no custom auth header
=> fix: set hasCustomAuthorizationHeader property on the AuthClient

package-lock.json, package.json
* bumps auth-js to v2.64.2 which contains these changes (https://github.com/supabase/auth-js/releases/tag/v2.64.2)
=> fix: bump auth-js to v2.64.2

.github/workflows/release.yml, .releaserc.json, jsr.json, package-lock.json, package.json, src/SupabaseClient.ts, src/index.ts, tsconfig.json
Publish to https://jsr.io/@supabase/supabase-js
=> fix: publish to jsr.

src/SupabaseClient.ts, src/lib/helpers.ts, test/helpers.test.ts
Internal, non-breaking change. `applySettingDefaults` enforces existence of all options namespaces, so they should not be optional anymore.
=> ref: Update applySettingDefaults typings to use accurate return type

package-lock.json, package.json, src/index.ts, tsconfig.json, tsconfig.module.json, wrapper.mjs
Follow up to https://github.com/supabase/postgrest-js/pull/537
=> fix: use proper dual packaging

package-lock.json, package.json
dependency update
Bump storage-js to v2.6.0
=> chore(deps): bump storage-js dependency

package-lock.json, package.json
Bump up realtime-js 2.10.2 - https://github.com/supabase/realtime-js/pull/412
=> fix: Bump up realtime-js 2.10.2

package-lock.json, package.json
* See [changelog](https://github.com/supabase/auth-js/compare/v2.64.2...v2.64.4)
=> fix: bump auth-js to v2.64.4

src/SupabaseClient.ts, src/lib/helpers.ts, src/lib/types.ts, test/client.test.ts
Adds support for the `accessToken` option on the Supabase client which can be used to provide a third-party authentication (e.g. Auth0, Clerk, Firebase Auth, ...) access token or ID token to be used instead of Supabase Auth.
When set, `supabase.auth.xyz` cannot be used and an error will be thrown.
=> feat: add third-party auth support

src/SupabaseClient.ts
Bug fix
You cannot pass a custom `lock` function to `createClient`. It's currently being lost  in the `_initSupabaseAuthClient()` function. The `lock` parameter is not being used.
A custom `lock` function will be used (and correctly passed to the GoTrueClient) inside the `_initSupabaseAuthClient()` function.
=> fix: Allow passing a custom lock function to supabase client

package-lock.json, package.json
Dep updated
storage-js version update, with support for metadata and exists.
=> fix: bump storage-js v2.7.0

package-lock.json, package.json
* bump auth-js to v2.65.0 (see changelog - https://github.com/supabase/auth-js/releases/tag/v2.65.0)
=> chore: bump auth-js to v2.65.0

package-lock.json, package.json
https://github.com/supabase/postgrest-js/compare/v1.15.8...v1.16.1
Fixes https://github.com/supabase/supabase/issues/29086
=> fix: bump postgrest-js to v1.16.1

package-lock.json, package.json
I just ran into the issue described in https://github.com/supabase/realtime/issues/282 — the `subscribe` does not mean that I'm successfully subscribed to `postgres_changes` - instead I need to listen on `'system'` messages for that confirmation, checking the `extension` and `status` properties, as @chasers described in that thread.
I searched around to see if the types for `@supabase/supabase-js` to include `'system'`, and was happily surprised to see that @filipecabaco added it in https://github.com/supabase/realtime-js/pull/422 last month.
Then I was confused to discover that this module hadn't been updated since then.
Thankfully a simple fix! Just updating these version numbers. I went ahead and update the other supabase modules that are behind their latest versions, too.
It would be …
=> Updates supabase sub-modules to latest versions

package-lock.json, package.json
Update @supabase/postgrest-js to v1.16.3
Type `PostgrestError` is not assignable to class `PostgrestError`: https://github.com/supabase/supabase-js/issues/1287
Type `PostgrestError` is removed, class `PostgrestError` is used instead
=> Update @supabase/postgrest-js to v1.16.3

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/types.ts, test/index.test-d.ts
This reverts commit 963d6a5b075eb813b6fd5d4feded367e837235df, reversing changes made to ce1e2f0729068a2bcd794cc3937da07d5d38677e.
=> fix: Revert "Merge pull request #1299 from supabase/rc"

package-lock.json, package.json, src/SupabaseClient.ts
Realtime using accessToken callback for auth
=> feat: Realtime using accessToken callback for auth

package-lock.json, package.json
* Changelog - https://github.com/supabase/auth-js/releases/tag/v2.66.1
=> fix: bump auth-js to v2.66.1

src/SupabaseClient.ts
call set auth for realtime on token changes
=> fix: call set auth for realtime on token changes

src/SupabaseClient.ts
This reverts commit 5e1e477a7dd4b24ce66fe737352b5ca6d9d3fdcb.
https://github.com/supabase/supabase-js/pull/1329
=> fix: revert set auth call

package-lock.json, package.json
* Bumps auth version to [v2.67.0](https://github.com/supabase/auth-js/releases/tag/v2.67.0)
=> fix: bump auth version to v2.67.0

package-lock.json, package.json
* Upgrades auth-js to [v2.67.3](https://github.com/supabase/auth-js/releases/tag/v2.67.3)
=> fix: update auth-js to v2.67.3

package-lock.json, package.json
Includes https://github.com/supabase/postgrest-js/pull/591
=> fix: Bump postgrest-js to 1.17.10

src/index.ts
Follow up to https://github.com/supabase/postgrest-js/pull/555
=> fix: export PostgrestError as a class

src/SupabaseClient.ts, src/lib/types.ts
Bug fix.
Reading through [the documentation](https://supabase.com/docs/guides/auth/third-party/firebase-auth?queryGroups=firebase-create-client&firebase-create-client=ts#setup-the-supabase-client-library), it looks like the return value of the `accessToken` should allow `null` to be returned, but the current type doesn't allow null to be returned. This PR updates the return type of the `accessToken` function to allow null to be returned.
The code sample from the docs has type error, because `null` cannot be returned from `accessToken` function.
```ts
import { createClient } from '@supabase/supabase-js'
const supabase = createClient('https://<supabase-project>.supabase.co', 'SUPABASE_ANON_KEY', {
accessToken: async () => {
return await firebase.auth().currentUser?.getIdToken(/* …
```
=> fix: Make the return value of accessToken nullable

src/SupabaseClient.ts
fixes the following bug : 
The left operand of the "??" operator here will never be null or undefined, so it will always be returned.
Bug fix
#1338
=> fix(lint): nullish coalescing operator issue in hasCustomAuthorizationHeader

package-lock.json, package.json
* bumps auth-js to [v2.69.0](https://github.com/supabase/auth-js/releases/tag/v2.69.0)
=> fix: bump auth-js to v2.69.0

src/SupabaseClient.ts, src/lib/helpers.ts, test/SupabaseClient.test.ts, test/helper.test.ts
This PR ensures that path segments in the `supabaseUrl` are preserved when constructing service endpoint URLs (e.g., auth, realtime, etc.). 
Fixes #1421.
Currently, any path component in the supabaseUrl is discarded when constructing endpoint URLs using the URL constructor.
Example:  `const supabase = createClient('https://example.com/path/to/supabase/', 'public-anon-key')` the resulting endpoint is incorrectly resolved as `https://example.com/realtime/v1`.
See #1421 for more context.
This fix preserves the full path in supabaseUrl when resolving endpoint URLs.
For example, if `supabaseUrl` is `https://example.com/path/to/supabase/`, the realtime endpoint will now correctly resolve to `https://example.com/path/to/supabase/realtime/v1`.
=> fix: preserve path segments in supabaseUrl when constructing endpoints.

package-lock.json, package.json
Use the latest release of functions-js
=> fix: bump functions-js to 2.4.5

package-lock.json, package.json, pnpm-lock.yaml, src/SupabaseClient.ts, test/unit/SupabaseClient.test.ts
* setAuth ran automatically for realtime
* prioritize setAuth tasks
* tried a new approach to test where we move to protected visibility so we have a test implementation for SupabaseClient that mostly binds protected to public methods
=> fix: setAuth ran automatically for realtime; prioritize setAuth tasks

package-lock.json, package.json
Releases `supabase.auth.getClaims()` as a non-experimental function.
=> feat: bump auth-js to 2.71.0

README.md
Add a new section to the README for outlining the scope of support for various runtime environments in Supabase JavaScript client.
=> chore: add support policy to README

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/helpers.ts, src/lib/types.ts
Feature
- Update [storage-js version ](https://github.com/supabase/storage-js/releases) to `v2.10.4`
- Includes `StorageClientOptions` in constructor
- Allows using direct storage host to optimize large uploads
- Adds support for Analytics Buckets
- Normalizes error handling when uploading objects
- Expose `StorageClientOptions` to allow passing storage specific settings to the storage client
=> feat: bump storage version, and expose StorageClientOptions

src/index.ts, test/unit/deprecation.test.ts
Bug fix - resolves Next.js Edge Runtime compatibility warnings
The Node.js deprecation warning introduced in v2.52.1 causes Next.js Edge Runtime build warnings when using `@supabase/supabase-js` in middleware, even though the code is properly guarded and won't execute in Edge Runtime.
The warnings appear as:
```
A Node.js API is used (process.version at line: 17) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
```
This PR modifies the deprecation warning check to use dynamic property access (`process['version']`) instead of direct property access (`process.version`). This prevents Next.js static analysis from flagging the code as incompatible with Edge Runtime while maintaining the exact same runtime behavior.
Key changes:
- Use …
=> fix: avoid Next.js Edge Runtime warnings in Node.js deprecation check

package-lock.json, package.json, src/SupabaseClient.ts, test/integration/node-browser/websocket.spec.ts
Bug fix - Fixes browser integration test failures caused by realtime authentication token resolution (to be introduced by https://github.com/supabase/realtime-js/pull/502).
Browser integration tests fail with "TimeoutError: Waiting for selector `#realtime_status` failed: Waiting failed: 2000ms exceeded" when attempting to establish realtime connections in unauthenticated contexts.
The issue was introduced by realtime-js v2.13.0 (PR [#502](https://github.com/supabase/realtime-js/pull/502)) which added mandatory API key validation to the RealtimeClient constructor. The constructor now throws `"API key is required to connect to Realtime"` if `options.params.apikey` is not provided.
In browser environments with unauthenticated users:
1. `_getAccessToken()` returns `null` when no session …
=> feat: fallback to key - update realtime js to 2.15.0

package-lock.json, package.json, src/SupabaseClient.ts, src/index.ts, test/integration/next/app/layout.tsx, test/integration/next/package.json, test/integration/next/tests/types/types.test-d.ts, test/integration/next/tsconfig.json, test/types/index.test-d.ts, test/unit/SupabaseClient.test.ts
pending on https://github.com/supabase/postgrest-js/pull/637
Additionally reimplement support for accepting a schema name in the second type param (e.g. `SupabaseClient<Database, 'my_schema'>`. We have a lot of users doing this: https://github.com/search?q=createClient%3CDatabase%2C+%22&type=code
=> feat: reland postgrest 13 support

package-lock.json, package.json
Bump functions-js to latest release 2.5.0
=> fix: bump functions-js to 2.5.0

package-lock.json, package.json, src/lib/types.ts
Change import. Goes together with this fix: https://github.com/supabase/storage-js/pull/255
Release breaks due to 
```
error: [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///home/runner/work/supabase-js/supabase-js/node_modules/@supabase/storage-js/dist/module/StorageClient' imported from 'file:///home/runner/work/supabase-js/supabase-js/src/lib/types.ts'
Did you mean to import with the ".js" extension?
at file:///home/runner/work/supabase-js/supabase-js/src/lib/types.ts:4:38
[1:19:18 PM] [semantic-release] [@sebbo2002/semantic-release-jsr] › ℹ  jsr publish failed after 2593 ms:
[1:19:18 PM] [semantic-release] [@sebbo2002/semantic-release-jsr] › ✖  Error: Child process exited with: 1
at ChildProcess.<anonymous> (/home/runner/work/supabase-js/supabase-js/node_modules/@sebbo2002/semantic- …
```
=> fix: update import of storageClientOptions

.github/workflows/ci.yml
Add a `fail-on-error: false` to `coveralls` uploads. 
Coveralls seems to be failing, and being flaky. 
If `coveralls` upload fails, the CI will not fail.
=> chore: do not fail on coveralls error

packages/core/auth-js/src/GoTrueClient.ts
If you pass in an async function to `onAuthStateChange` and call a Supabase Client API, it's very likely you'll end up with a deadlock. Example:
```typescript
supabase.auth.onAuthStateChange(async () => {
await supabase.auth.getClaims()
})
```
This is because:
- `onAuthStateChange` runs inside an exclusive lock
- If you call another API that tries to acquire the exclusive lock, the initial call will never finish, thereby never releasing the first lock, and no other Auth API can be called (across all tabs)
Multiple attempts were made to detect these situations but it's not easy as async functions don't track execution context in all environments properly.
This change adds a deprecation notice if the callback is an async function to discourage folks from using it, and hopefully make it a …
=> feat(auth): add deprecation notice to `onAuthStateChange` with async function

packages/core/auth-js/src/GoTrueAdminApi.ts, packages/core/auth-js/src/lib/types.ts
Adds OAuth 2.1 client administration endpoints to `@supabase/auth-js` based on the OpenAPI specification from https://github.com/supabase/auth/pull/2165.
This PR implements a new `admin.oauth` namespace with full CRUD operations for managing OAuth clients when the OAuth 2.1 server is enabled in Supabase Auth
New admin.oauth methods:
- listClients() - List OAuth clients with pagination (for now, the same api with `listUsers`)
- createClient() - Register new OAuth client
- getClient() - Get client details by ID
- deleteClient() - Remove OAuth client
- regenerateClientSecret() - Regenerate client secret
All methods include proper error handling, follow existing patterns (similar to admin.mfa), and are only relevant when the OAuth 2.1 server is enabled in Supabase Auth.
=> feat(auth): add OAuth 2.1 client admin endpoints

.github/workflows/publish.yml
To use [trusted publishers](https://docs.npmjs.com/trusted-publishers) the npm cli version must be `11.5.1` or greater.
=> chore(ci): bump npm cli version
