supabase/supabase-js

src/Auth.js
=> fix: #22 wont throw error for confirmation email signups

README.md
Bug fix - Update docs links on README
=> Update docs links on README

package-lock.json, webpack.config.js
Bug fix.
Ref: https://github.com/supabase/supabase-js/issues/113.
=> fix: process is undefined issue

src/lib/SupabaseRealtimeClient.ts
This PR will help us to reduce the complexity of the SupabaseRealtimeClient class splitting our current code.
SupabaseRealtimeClient Class complexity is 14.
SupabaseRealtimeClient Class complexity will be 10.
=> refactor: reducing the complexity of the SupabaseRealtimeClient class

src/lib/storage/fetch.ts
Nothing, just to trigger the release cause I missed out the semantics in my commit messages previously
=> feat: add abort controller signal to storage list method

src/lib/storage/StorageFileApi.ts
Fixes incorrect type on upload API call.
=> fix: types for upload object

package-lock.json, package.json
=> feat: update storage-js

package-lock.json, package.json
Feature, bug fix.
Closes #168, closes #206.
https://github.com/supabase/supabase/discussions/2015.
https://github.com/supabase/supabase/discussions/1834
=> Bump postgrest-js

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/types.ts
Feature
Passes along constructor options to realtime-js
Depends on https://github.com/supabase/realtime-js/pull/95 before merge.
=> Pass along realtime-js options

src/lib/constants.ts
=> fix: require -> import

README.md
Update our documentation to make it easier for all users to correctly understand how to install and use the library
=> docs: update project's documentation

.github/workflows/ci.yml, example/next-todo/package-lock.json, example/next-todo/package.json, jest.config.js, package-lock.json, package.json, src/SupabaseClient.ts, src/lib/constants.ts, src/lib/helpers.ts, test/helpers.test.ts
- gotrue-js should now be handled across browser windows/tabs by default
- client will keep socket connections fresh with all auth events
=> fix: improve auth for realtime row level security

src/SupabaseClient.ts, src/lib/SupabaseQueryBuilder.ts
Bug fix
1. A new Realtime subscription is created whenever SupabaseClient `from` method is called, even when user does not intend on using Realtime.
2. Realtime channel is not cleaned up properly from the list of channels on the RealtimeClient. Channel is only removed when it is open and then closed. There are cases, like mentioned above, where a subscription is created but never subscribed to. This causes state to be closed which means the subscription is never cleaned up.
1. Subscription is created only when intended; when SupabaseQueryBuilder `on` method is called.
2. SupabaseClient does a better job of cleaning up subscriptions regardless of the state.
- Related issue: https://github.com/supabase/supabase/issues/4451
- `removeAllSubscriptions` method on the SupabaseClient can be used …
=> fix: create subscription only when .on method is called

src/lib/SupabaseRealtimeClient.ts, src/lib/types.ts
feature
Realtime RLS (WALRUS) has error states that will output error messages. This PR will add errors to the payload.
WALRUS error states: https://github.com/supabase/walrus#error-states
=> feat: add errors to Realtime payload

package-lock.json, package.json
Bug fix
See issue: https://github.com/supabase/realtime-js/issues/123
See realtime-js PR: https://github.com/supabase/realtime-js/pull/126
=> fix: version bump realtime-js to v1.3.4

package-lock.json, package.json
issue: https://github.com/supabase/realtime-js/issues/127
pr: https://github.com/supabase/realtime-js/pull/128
=> fix: enforce Realtime unique subscriptions per client

src/SupabaseClient.ts
=> Removed unnecessary async

src/SupabaseClient.ts
feature
when a user signs out, the client with update realtime subscriptions from the user's access token, where claims role is `authenticated`, to the access token where role is `anon`. this will allow signed out users to continue to listen to changes depending on rls policies without missing messages as long as they have permission.
Other improvements:
- client.removeSubscription(subscription) will close and remove a subscription and return a promise of an object with error and the number of open subscriptions remaining:
e.g.
```js
{
data: { openSubscriptions: 10 },
error: null | Error
}
```
- client.removeAllSubscriptions() will close and remove all subscriptions and return a promise of an array of objects with the subscription and error:
e.g.
```js
[{
data: { subscription: …
```
=> feat: refactor Realtime subscription methods

README.md
Added instructions on how to use the browser ESM.
=> Added instructions on how to use the browser ESM.

package-lock.json, package.json
See https://github.com/supabase/realtime-js/pull/134.
=> fix: Realtime heartbeat ref reset on message

example/next-ts/next-env.d.ts, example/next-ts/package-lock.json, example/next-ts/pages/api/supa-function.ts, example/next-ts/tsconfig.json, example/next-ts/yarn.lock, package-lock.json, package.json, src/SupabaseClient.ts, src/lib/types.ts
=> feat: add functions-js

package-lock.json, package.json
=> Bump package versions

package-lock.json, package.json, src/SupabaseClient.ts
feature
Add Realtime Channel (Broadcast and Presence)  functionality through `channel` method.
=> feat: add channel to SupabaseClient

package-lock.json, package.json
Bug fix
https://github.com/supabase/realtime-js/pull/156
=> fix: version bump realtime-js to 1.7.1

src/SupabaseClient.ts, src/lib/types.ts
allow customize cookie options on auth client
=> feat(auth): add cookieOptions for underliying auth client

package-lock.json, package.json
Bug fix
https://github.com/supabase/gotrue-js/pull/273
=> fix: version bump gotrue-js to 1.22.13

package-lock.json, package.json
Bug fix
See: https://github.com/supabase/realtime-js/pull/158
=> fix: version bump realtime-js to 1.7.2

README.md
=> update(README.md): replace `.io` to `.com`

package-lock.json, package.json
=> fix: version bump gotrue-js to 1.22.14

src/SupabaseClient.ts, src/lib/fetch.ts
fix: include apikey in custom fetch
=> fix: include apikey in custom fetch

package-lock.json, package.json
Updates `gotrue-js` from `1.23.0-next.1` to `1.23.0-next.2`
=> chore(deps): update gotrue-js

package-lock.json, package.json
* Includes addition of captcha to `signIn` method
=> fix: bump gotrue version

package-lock.json, package.json, src/SupabaseClient.ts, src/lib/types.ts
* Bump gotrue-js to latest next version
=> fix: bump gotrue js version

src/SupabaseClient.ts
Allow fallback to generic string
=> fix: from method typings

src/SupabaseClient.ts, src/lib/helpers.ts, src/lib/types.ts, test/SupabaseAuthClient.test.ts, test/client.test.ts, test/helpers.test.ts
Draws heavily on the work done in #499 
Here's an image of a manual test:
input options:
Sample output:
=> Patch revamped constructor

example/next-storage/components/ProfileList.tsx, example/next-storage/package-lock.json, example/next-storage/package.json, example/next-todo/components/TodoList.js, example/next-todo/package-lock.json, package-lock.json, package.json, src/SupabaseClient.ts, src/index.ts, src/lib/SupabaseQueryBuilder.ts, src/lib/SupabaseRealtimeClient.ts, src/lib/types.ts
This reverts commit bd03b65e2f9d2e73499e44cbf2b791082237b5de, reversing
changes made to f37643c690f19371f00b25a2fda2795cde899c54.
Roll back Realtime v2 API changes until all projects are migrated over to Multi-Tenant Realtime cluster.
=> Revert "Merge pull request #462 from supabase/feat/new-realtime-api"

package-lock.json, package.json
=> fix: bump gotrue-js version

src/SupabaseClient.ts, src/lib/types.ts
Forgot to update typings in https://github.com/supabase/supabase-js/pull/547
Fixes #548
=> fix: typings

package-lock.json, package.json
Bug fix
Issue: https://github.com/supabase/realtime-js/issues/169
Realtime client fix: https://github.com/supabase/realtime-js/pull/192
=> fix: keep second channel with same topic open on rapid re-subscribe

package-lock.json, package.json
* Updates gotrue to the latest rc version
=> fix: bump supabase-js version

README.md
Updated link to avoid a redirect.
https://supabase.com/docs/client/supabase-client >> https://supabase.com/docs/reference
=> Updated link to avoid a redirect.

package-lock.json, package.json
Bug fix
Improved types for database changes.
=> fix: upgrade realtime-js to v2.1.0 to fix PG change types

package-lock.json, package.json, src/SupabaseClient.ts
bug fix
Bump postgrest-js and fix typings.
Closes #602
=> fix(deps): bump postgrest-js

package-lock.json, package.json
Includes experimental MFA bindings(Disabled by default)
=> chore: bump gotrue to v2.1.0

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release.yml
=> chore: bump node to 16

package-lock.json, package.json
=> fix: bump gotrue version to v2.2.0

README.md
Docs update
Readme shows v1 usage.
Readme shows v2 usage.
=> chore: Update readme with correct arguments for custom fetch

package-lock.json, package.json
Bumps gotrue-js from 2.2.4 to 2.3.0.
=> feat: bump gotrue-js to 2.3.0

package-lock.json, package.json
https://github.com/supabase/postgrest-js/pull/379
=> fix(deps): bump postgrest-js to ^1.1.1

package-lock.json, package.json
* Fix bug in `supabase.auth.admin.mfa.listFactors` method
* Add pagination support to `supabase.auth.admin.listUsers`
=> fix: bump gotrue-js to v2.6.1

package-lock.json, package.json
This PR bumps functions-js to 2.1.0 which includes support for invoking functions with different HTTP methods.
=> feat: bump functions-js version

package-lock.json, package.json
=> feat: bump gotrue to 2.18.1

package-lock.json, package.json
=> feat: bump gotrue-js to v2.21

package-lock.json, package.json
=> feat: bump storage

package-lock.json, package.json
=> feat: bump gotrue version to 2.23

package-lock.json, package.json
=> feat: update gotrue version to v2.26

src/SupabaseClient.ts
feature
Invoke functions with `/functions/v1` path prefix allowing us to support custom domains and vanity domains for edge functions
=> feat: edge functions support for custom domains and vanity domains

.github/workflows/ci.yml
Added paths-ignore option for running ci tests only when certain files change
closes #791
=> ci: added paths-ignore option

package-lock.json, package.json
=> feat: bump gotrue-js to v2.45.0

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release.yml
Node 16 will be reaching EOL in september
=> feat: bump node version to 18

package-lock.json, package.json, src/lib/fetch.ts
Fixes https://github.com/supabase/supabase-js/issues/612.
=> fix: replace cross-fetch with @supabase/node-fetch

package-lock.json, package.json
https://github.com/supabase/postgrest-js/pull/486
=> fix: bump postgrest-js to 1.8.5

package-lock.json, package.json
=> chore: Bump up Realtime to 2.8.1

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release.yml
It updates the node version
N/A 
N/A 
N/A
=> chore: update node version in ci

README.md
=> docs: Add Deno how-to to README.md

src/SupabaseClient.ts
Reverts:
- https://github.com/supabase/supabase-js/pull/975
- https://github.com/supabase/supabase-js/pull/973
=> fix: revert from/schema/rpc changes

package-lock.json, package.json, src/index.ts
=> feat: bump functions-js (get regional types more integrated)

package-lock.json, package.json
Includes https://github.com/supabase/postgrest-js/pull/529
=> feat: bump postgrest-js to v1.15.0

package-lock.json, package.json
https://github.com/supabase/postgrest-js/pull/534
=> fix(postgrest-js): bump to 1.15.2

package-lock.json, package.json
=> fix: bump dependencies.

package-lock.json, package.json
=> feat: Bump realtime-js 2.10.1

package-lock.json, package.json
Fixes https://github.com/supabase/supabase-js/issues/1229, fixes https://github.com/supabase/supabase-js/issues/1230
=> fix: postgrest-js esm typings

package-lock.json, package.json
Fixes https://github.com/supabase/supabase-js/issues/1238
=> fix: imports not working w/ Metro bundler

src/SupabaseClient.ts
Follow up to https://github.com/supabase/supabase-js/pull/1285
=> fix: update rpc types

.github/workflows/docs.yml
Related to #1281 
Updated Github Action's version
=> Updated Github Action's version

package-lock.json, package.json, test/index.test-d.ts
https://github.com/supabase/postgrest-js/compare/v1.17.0-rc.1...v1.17.0-rc.3
Resolves many-to-many relationships ([context](https://github.com/supabase/postgrest-js/pull/565))
=> fix: types tests

package-lock.json, package.json, test/index.test-d.ts
- Upgrade posgrest-js to rc.4
- Fix error test type
=> chore(deps): upgrade postgest-js to rc.4

.github/workflows/docs.yml, package-lock.json, package.json
No changes in code, just uses a stable version of postgrest-js in preparation for a new stable version on supabase-js
=> feat: postgrest-js 1.17.0

package-lock.json, package.json
=> chore(deps): bump postgrest-js to 1.17.4

package-lock.json, package.json
=> chore(deps): upgrade postgres-js to 1.17.5

README.md
=> fix: cut release

package-lock.json, package.json
=> fix: bump up realtime-js

package-lock.json, package.json, src/SupabaseClient.ts
Revert "feat: Realtime using accessToken callback for auth (#1320)"
This reverts commit 88a44dfbfdf336f616bfd59a3137a35afc88b0dc.
=> fix: Realtime using accessToken callback for auth

package-lock.json, package.json, src/SupabaseClient.ts
Bind proper object to setAuth on Realtime callback
=> fix: Bind proper object to setAuth on Realtime callback

package-lock.json, package.json, src/SupabaseClient.ts
=> chore: upgrade rc for release

package-lock.json, package.json
=> fix: update auth version to 2.67.1

package-lock.json, package.json
=> fix: bump functions-js to 2.4.4

package-lock.json, package.json, test/index.test-d.ts
=> fix: bump postgrest-js to 1.17.11

package-lock.json, package.json
- Adding JSON path type inference capability
=> feat(deps): bump postgrest-js to 1.18.0

package-lock.json, package.json
=> fix(types): bump postgrest-js 1.18.1

package-lock.json, package.json
Should be merged with: https://github.com/supabase/supabase/pull/33705 for docs
=> fix(deps): upgrade postgrest-js 1.19.2

README.md
=> chore: add open role to README.md

package-lock.json, package.json
Fixes an issue with 2.69.0 which had problems with PKCE.
=> fix: bump auth-js to 2.69.1

package-lock.json, package.json
Follow up: https://github.com/supabase/postgrest-js/pull/612
Fixes: #1368
=> chore(deps): upgrade postgres-js to 1.19.4

package-lock.json, package.json, src/SupabaseClient.ts
bump up realtime-js; await on token change
=> fix: bump up realtime-js; await on token change

package-lock.json, package.json, pnpm-lock.yaml
=> bump up realtime-js

package-lock.json, package.json, pnpm-lock.yaml
=> fix: bump up realtime

README.md
=> chore: remove hiring link from README.md

.github/workflows/ci.yml, package.json, test/integration/expo/package-lock.json, test/integration/expo/package.json, test/integration/node-browser/index.html, test/integration/node-browser/package.json, test/integration/node-browser/playwright.config.ts, test/integration/node-browser/websocket.spec.ts
- returned deno browser test
- added basic websocket playwright test for chromium, firefox and webkit.
- moved build and pack steps to the separate stage before runnning tests
=> test: add browser test to check websocket constructor

.github/workflows/ci.yml, package.json, src/SupabaseClient.ts
=> verify jsr packaging rules

package-lock.json, package.json, pnpm-lock.yaml
=> fix: bump up realtime js

package-lock.json, package.json
bump auth-js to 2.71.1. fixes #1504
=> feat: bump auth-js to 2.71.1

package-lock.json, package.json
=> feat: bump auth-js to 2.72.0
